### ISSUE TITLE
About the scale factor in real-world track

### ISSUE THREAD

**Issue by NiPaung** [goutamgmb/NTIRE21_BURSTSR#1]
hello, i wonder the scale factor of the real-world track.

The description section of this github says that the goal is to predict 4 times higher resolution image.
However, In train and validation datasets, HR images 8 times larger than LR images and python code is written to set scale factor with x8.

Is it correct to set the scale as provided in the python toolkit?

**Comment by goutamgmb** [comment]
Hi,

Given the s x s RAW bayer mosaic as input, the task is to predict a 4s x 4s RGB image. However, we pack the RAW image as a 4 channel tensor s/2 x s/2 x 4, where the channels correspond to the R, G, G, B values. Hence there is an additional 2x factor to perform demosaicking. 

Regards
