### ISSUE TITLE
Meta data in the test phase

### ISSUE THREAD

**Issue by Magauiya** [goutamgmb/NTIRE21_BURSTSR#12]
Dear Organizers,

In the validation set for Track 1, there is no meta data, but for the Track 2 validation images contain meta info. So, will you provide meta data (e.g. ISO, noise level, etc) in the test phase for both tracks? 

Thanks.

**Comment by goutamgmb** [comment]
Hi,

No.  We will provide the same data which was provided for the validation phase. Thus we won't be releasing the meta data for track 1.
