### ISSUE TITLE
Can we submit results to the test server of Colab

### ISSUE THREAD

**Issue by Algolzw** [goutamgmb/NTIRE21_BURSTSR#15]
An error
![image](https://user-images.githubusercontent.com/15884127/111273648-08ad5080-866f-11eb-84f5-866519f37962.png)

**Comment by goutamgmb** [comment]
Hi,

No, the evaluation server is not supported for the test set. You can upload the results using the google form. The results will be notified to you after the submission deadline.

**Comment by Algolzw** [comment]
Thanks
