### ISSUE TITLE
How do you calculate PSNR in the test phase?

### ISSUE THREAD

**Issue by Magauiya** [goutamgmb/NTIRE21_BURSTSR#16]
Dear Organizers,

According to the metrics provided [here](https://github.com/goutamgmb/NTIRE21_BURSTSR/blob/e1dbd4a707c280ef613319e2b160a84df55d9dd7/utils/metrics.py#L37), PSNR is calculated by ignoring image borders. 

1. So, will you use this PSNR code to evaluate images in the test phase? 
2. If yes, then what will be the boundary_ignore parameter?

Thank you!

**Comment by goutamgmb** [comment]
Hi,

Yes, we will use the same script for score. The boundary_ignore parameter will be set to 40.
