### ISSUE TITLE
Question about the factsheet

### ISSUE THREAD

**Issue by Algolzw** [goutamgmb/NTIRE21_BURSTSR#17]
Dear Sir,
Do we need to submit two factsheets?
Our pipelines and modules are different for each track.

**Comment by goutamgmb** [comment]
Hi,

You can either describe both methods separately in a single fact sheet, or just include two separate factsheets in the zip folder. However, please use a single submission form for both the tracks.

**Comment by Algolzw** [comment]
thanks
