### ISSUE TITLE
Question about pwcnet and warp

### ISSUE THREAD

**Issue by Nianzhen-GU** [goutamgmb/NTIRE21_BURSTSR#26]
Hello! I use the PWC-Net code in your GitHub to calculate the optical from the first image to the second image and warped the second back to the first using the optical flow. However, the warped image is blurred. I want to know whether it is difficult to warp two images with large difference or it is my fault that my optical flow is wrong.
![chair2](https://user-images.githubusercontent.com/80320541/130369325-77426956-b37a-4ecf-97fa-4ec29547efbd.png)
![chair5](https://user-images.githubusercontent.com/80320541/130369327-af2b1a67-a350-4ada-acbd-30f4467f512b.png)
![flo2-5](https://user-images.githubusercontent.com/80320541/130369329-ea61a4b9-9260-4754-baf3-42cbdcc052b4.png)
![warped](https://user-images.githubusercontent.com/80320541/130369334-42bfb89a-0ad8-46f6-ab70-c41bd2a40c34.png)

**Comment by goutamgmb** [comment]
Hi,

Its hard to say looking at the results whether there is any bug in the optical flow computation itself.  But the two images have substantial view point changes. In general the optical flow networks are trained to handle smaller viewpoint changes, and thus cannot be expected to accurately handle large view point changes present in your examples. You can try using geometric correspondence networks (e.g. https://github.com/PruneTruong/DenseMatching) which are specifically trained to handle these large motions.

**Comment by Nianzhen-GU** [comment]
Thanks alot!
