### ISSUE TITLE
Question about the evaluation code, simple bilinear model get PSNR 47.784!

### ISSUE THREAD

**Issue by Algolzw** [goutamgmb/NTIRE21_BURSTSR#3]
Hello, I run "evaluate_burstsr_val.py" to evaluate the SimpleBaseline (bilinear model), the PSNR of the first real-world validation data is 47.784! Is there something wrong?

**Comment by goutamgmb** [comment]
No, this is expected. The image intensity values in the BurstSR RAW images are generally small, with a mean of around 0.1 - 0.2. As a result, the PSNR values are generally very high, since the maximum signal value in the PSNR computation is still assumed to be 1.0.

**Comment by Algolzw** [comment]
OK, thanks!

**Comment by greatlog** [comment]
why I get 41.74 instead?
