### ISSUE TITLE
Submission error: Exception: Expected 300 .png images!

### ISSUE THREAD

**Issue by Algolzw** [goutamgmb/NTIRE21_BURSTSR#4]
I submitted a .zip containing 300 output (.png format), but always failed.
 
![image](https://user-images.githubusercontent.com/15884127/106774686-581a5d00-667d-11eb-9cb3-b391911c92fc.png)

**Comment by Algolzw** [comment]
The official example submission file is also failed.

**Comment by goutamgmb** [comment]
Hi,

Did you check the new example submission we uploaded yesterday? The older submission example had an error. 

The zip file you upload should directly contain the 300 images. The file you uploaded contains an additional sub-directory 'results', which contains the images. Hence the error.

**Comment by Algolzw** [comment]
Thanks!
