### ISSUE TITLE
About the color of result image 

### ISSUE THREAD

**Issue by yulei1234** [goutamgmb/NTIRE21_BURSTSR#9]
Hello，why is the color of the final test image so abnormal? Which link is the problem?
![image](https://user-images.githubusercontent.com/37969091/109099021-5106dc00-775d-11eb-917b-6074fa33dc5a.png)

**Comment by goutamgmb** [comment]
The images are stored as 4 channel, 16 bit pngs. Hence they are visualized weirdly. I do not think there is any issue with any of the download links.

**Comment by yulei1234** [comment]
ok，thanks
